### ISSUE TITLE
靓仔找工作吗

### ISSUE THREAD

**Issue by septem1997** [ChenHaoJie9527/momoco#10]
不好意思, github没有私信功能, 占用一下issue

**Comment by ChenHaoJie9527** [comment]
啊？！被你发现了，失业中🤣🤣

**Comment by septem1997** [comment]
其实是boss上看到的,感觉你挺符合要求的, 不过我们的岗位是在佛山, 你期望广州, 所以不能直接跟你沟通, 可以的话我们联系一下, 你发我简历,我发你JD
邮箱: 750627595@qq.com

**Comment by ChenHaoJie9527** [comment]
可以方便透露下是做什么的吗？

**Comment by septem1997** [comment]
> 可以方便透露下是做什么的吗？

<img width="171" alt="image" src="https://github.com/user-attachments/assets/483008b1-eeff-4428-a57a-d71a40bc6743">
